function logError(jqXHR,textStatus,errorThrown){console.log('Error! '+textStatus);console.log(errorThrown);console.log(jqXHR);}
var ECOMAX_850P_TYPE=0;var ECOMAX_850i_TYPE=1;function Controller(destination,ecosrv_address){this.destination_=destination;this.ecosrvAddress_=ecosrv_address;this.protocol_type='';this.type_=0;this.setProtocolType=function(t){if(typeof t==="string"){this.protocol_type=t.toLowerCase();}};this.setType=function(t){if(typeof t==="number"){this.type_=t;}else{console.log("Warning: wrong type for Controller.setType()");}};this.getRemoteMenuLangs=function(responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmLangs?uid="+encodeURIComponent(updater.currentDevice_):"rmLangs"),success:responseMethod,error:logError});return false;};this.getCurrentParamsEdits=function(responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmCurrentDataParamsEdits?uid="+encodeURIComponent(updater.currentDevice_):"rmCurrentDataParamsEdits"),success:responseMethod,error:logError});return false;};this.getRemoteMenuParamsNames=function(responseMethod,lang){if(lang==null&&updater.currentDevice_){lang=getRmLang();}
$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmParamsNames?uid="+encodeURIComponent(updater.currentDevice_)+"&lang="+encodeURIComponent(lang):"rmParamsNames"),success:responseMethod,error:logError});return false;};this.getRemoteMenuCatsNames=function(responseMethod,lang){if(lang==null&&updater.currentDevice_){lang=getRmLang();}
$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmCatsNames?uid="+encodeURIComponent(updater.currentDevice_)+"&lang="+encodeURIComponent(lang):"rmCatsNames"),success:responseMethod,error:logError});return false;};this.getRemoteMenuParamsUnitsNames=function(responseMethod,lang){if(lang==null&&updater.currentDevice_){lang=getRmLang();}
$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmParamsUnitsNames?uid="+encodeURIComponent(updater.currentDevice_)+"&lang="+encodeURIComponent(lang):"rmParamsUnitsNames"),success:responseMethod,error:logError});return false;};this.getRemoteMenuParamsEnums=function(responseMethod,lang){if(lang==null&&updater.currentDevice_){lang=getRmLang();}
$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmParamsEnums?uid="+encodeURIComponent(updater.currentDevice_)+"&lang="+encodeURIComponent(lang):"rmParamsEnums"),success:responseMethod,error:logError});return false;};this.getRemoteMenuLocksNames=function(responseMethod,lang){if(lang==null&&updater.currentDevice_){lang=getRmLang();}
$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmLocksNames?uid="+encodeURIComponent(updater.currentDevice_)+"&lang="+encodeURIComponent(lang):"rmLocksNames"),success:responseMethod,error:logError});return false;};this.getRemoteMenuStructure=function(responseMethod,lang){if(lang==null&&updater.currentDevice_){lang=getRmLang();}
$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmStructure?uid="+encodeURIComponent(updater.currentDevice_)+"&lang="+encodeURIComponent(lang):"rmStructure"),success:responseMethod,error:logError});return false;};this.getRemoteMenuCurrDataDisp=function(responseMethod,lang){if(lang==null&&updater.currentDevice_){lang=getRmLang();}
$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmCurrentDataParams?uid="+encodeURIComponent(updater.currentDevice_)+"&lang="+encodeURIComponent(lang):"rmCurrentDataParams"),success:responseMethod,error:logError});return false;};this.getRemoteMenuParamsData=function(responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmParamsData?uid="+encodeURIComponent(updater.currentDevice_):"rmParamsData"),success:responseMethod,error:logError});return false;};this.getRemoteMenuExistingLangsList=function(responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmExistingLangs?uid="+encodeURIComponent(updater.currentDevice_):"rmExistingLangs"),success:responseMethod,error:logError});return false;};this.getRemoteMenuAlarmsNames=function(responseMethod,lang){if(lang==null&&updater.currentDevice_){lang=getRmLang();}
$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmAlarmsNames?uid="+encodeURIComponent(updater.currentDevice_)+"&lang="+encodeURIComponent(lang):"rmAlarmsNames"),success:responseMethod,error:logError});return false;};this.getRemoteMenuParamsDescs=function(responseMethod,lang){if(lang==null&&updater.currentDevice_){lang=getRmLang();}
$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmParamsDescs?uid="+encodeURIComponent(updater.currentDevice_)+"&lang="+encodeURIComponent(lang):"rmParamsDescs"),success:responseMethod,error:logError});return false;};this.getRemoteMenuCatsDescs=function(responseMethod,lang){if(lang==null&&updater.currentDevice_){lang=getRmLang();}
$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmCatsDescs?uid="+encodeURIComponent(updater.currentDevice_)+"&lang="+encodeURIComponent(lang):"rmCatsDescs"),success:responseMethod,error:logError});return false;};this.getPassword=function(responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"call/run/getServicePassword?uid="+encodeURIComponent(updater.currentDevice_):"password"),success:responseMethod,error:logError});};this.getETPassword=function(responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"getETservicePasswords?uid="+encodeURIComponent(updater.currentDevice_):"etpassword"),success:responseMethod,error:logError});};this.updateSoftware=function(responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"updateEconet?uid="+updater.currentDevice_:"updateSoftware"),success:responseMethod,error:errorMethod});};this.saveParam=function(name,value,responseMethod,errorMethod,bit){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"newParam?uid="+encodeURIComponent(updater.currentDevice_)+"&":"newParam?")+
"newParamName="+encodeURIComponent(name)+"&newParamValue="+encodeURIComponent(value),success:responseMethod,error:errorMethod});return false;};this.rmSaveParam=function(index,value,responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmNewParam?uid="+encodeURIComponent(updater.currentDevice_)+"&":"rmNewParam?")+
"newParamIndex="+encodeURIComponent(index)+"&newParamValue="+encodeURIComponent(value),success:responseMethod,error:errorMethod});return false;};this.rmSaveCurrParam=function(key,value,responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmCurrNewParam?uid="+encodeURIComponent(updater.currentDevice_)+"&":"rmCurrNewParam?")+
"newParamKey="+encodeURIComponent(key)+"&newParamValue="+encodeURIComponent(value),success:responseMethod,error:errorMethod});return false;};this.rmCheckAccess=function(password,responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmAccess?uid="+encodeURIComponent(updater.currentDevice_)+"&":"rmAccess?")+
"password="+encodeURIComponent(password),success:responseMethod,error:errorMethod});return false;};this.rmSaveLang=function(value,responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"rmSaveLang?uid="+encodeURIComponent(updater.currentDevice_)+"&":"rmSaveLang?")+
"lang="+encodeURIComponent(value),success:responseMethod,error:logError});return false;};this.saveSchedules=function(param,mode,value,responseMethod,scheduleDev){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"saveSchedules?uid="+encodeURIComponent(updater.currentDevice_)+"&":"setSchedule?")+
"scheduleType="+encodeURIComponent(param)+"&timeOfWeek="+encodeURIComponent(mode)+"&values="+encodeURIComponent(value)+"&scheduleDev="+encodeURIComponent(scheduleDev),success:responseMethod,error:logError});return false;};this.saveScheduleVent=function(data,param,value,responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"saveVentSchedules?uid="+encodeURIComponent(updater.currentDevice_)+"&data="+encodeURIComponent(data)+"&param="+encodeURIComponent(param)+"&value="+encodeURIComponent(value),success:responseMethod,error:logError});return false;};this.getSchedules=function(responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+(updater.currentDevice_?"getSchedule?uid="+encodeURIComponent(updater.currentDevice_)+"&":"getSchedule?"),success:responseMethod,error:logError});return false;};this.checkSoftUpdate=function(protocol,routertype,responseMethod){if(routertype!=undefined){routerparam="&router="+encodeURIComponent(routertype);}else{routerparam=""}
$.ajax({type:"GET",contentType:"json",cache:false,url:this.destination_+"checkSoftwareUpdate?protocol="+encodeURIComponent(protocol)+routerparam,error:logError,success:responseMethod,beforeSend:function(xhr){xhr.setRequestHeader("X-CSRFToken",Cookies.get('csrftoken'));}});return false;};this.getETtranslations=function(ver,client,lang,responseMethod,errorMethod){if(ver==null||client==null||schema.controllerID==null||schema.controllerID==""){return false;errorMethod();}
$.ajax({type:"POST",contentType:"json",data:{"ver":(ver.length>0)?ver:"","client":client,"lang":lang,"regName":schema.controllerID,},headers:{Accept:"json","Content-Type":"application/x-www-form-urlencoded"},cache:true,url:document.location.protocol+"//"+this.ecosrvAddress_+"/service/getETtranslations/",error:errorMethod,success:responseMethod,});return false;};Controller.prototype.saveAlertDateUser=function(userDate){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"saveAlertDateUser?"+"userDate="+encodeURIComponent(userDate),error:logError})};}
Controller.prototype.getDevices=function(responseMethod,active,notactive,blocked,type,uid,prodId,page,softVer,mod_a_ver=null,panel_ver=null){$('#devsNumber').text(translate("searching_ctrl"))
$('#devs_loader').show()
if(typeof GROUP_MANAGEMENT!=='undefined'&&!(isMemberOfGroup(GROUP_MANAGEMENT))){blocked=false;}
$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getDevices?"+"active="+encodeURIComponent(active)+"&notactive="+encodeURIComponent(notactive)+
"&blocked="+encodeURIComponent(blocked)+"&deviceType="+encodeURIComponent(type)+"&uid="+encodeURIComponent(uid)+"&prodId="+encodeURIComponent(prodId)+"&page="+page+"&softVer="+encodeURIComponent(softVer)+((mod_a_ver!==null)?"&v_mod_a="+encodeURIComponent(mod_a_ver):"")+((panel_ver!==null)?"&v_panel="+encodeURIComponent(panel_ver):""),success:responseMethod,error:logError});};Controller.prototype.getAlertsDates=function(responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getAlertsDates",success:responseMethod,error:logError});};Controller.prototype.getCurrentState=function(responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getCurrentState",success:responseMethod,error:logError});};Controller.prototype.getDeviceParams=function(uid,responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getDeviceParams?uid="+encodeURIComponent(uid.toString()),success:responseMethod,error:logError});};Controller.prototype.getDeviceRegParams=function(uid,responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getDeviceRegParams?uid="+encodeURIComponent(uid.toString()),success:responseMethod,error:logError});};Controller.prototype.getHistoryParamsValues=function(uid,fromDate,toDate,responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getHistoryParamsValues?uid="+encodeURIComponent(uid)+
"&fromDate="+encodeURIComponent(fromDate)+"&toDate="+encodeURIComponent(toDate),success:responseMethod,error:getHistoryParamValuesError});};Controller.prototype.getDeviceSysParams=function(uid,responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getDeviceSysParams?uid="+encodeURIComponent(uid.toString()),success:responseMethod,error:logError});};Controller.prototype.getDeviceEditableParams=function(uid,responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getDeviceEditableParams?uid="+encodeURIComponent(uid.toString()),success:responseMethod,error:logError});};Controller.prototype.getDeviceAlarms=function(uid,responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getDeviceAlarms?uid="+encodeURIComponent(uid.toString()),success:responseMethod,error:logError});};Controller.prototype.setDeviceSettings=function(uid,label,serviceAccess,alarmNotifications,responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"setDevSettings?uid="+encodeURIComponent(uid.toString())
+"&label="+encodeURIComponent(label)
+"&serviceAccess="+encodeURIComponent(serviceAccess)
+"&alarmNotifications="+encodeURIComponent(alarmNotifications),success:responseMethod,error:logError});};Controller.prototype.setDeviceAddressSettings=function(uid,street,house,apartment,postalCode,city,country,responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"setDevAddrSettings?uid="+encodeURIComponent(uid.toString())
+"&street="+encodeURIComponent(street)
+"&house="+encodeURIComponent(house)
+"&apartment="+encodeURIComponent(apartment)
+"&postalCode="+encodeURIComponent(postalCode)
+"&city="+encodeURIComponent(city)
+"&country="+encodeURIComponent(country),success:responseMethod,error:logError});};Controller.prototype.changeAdvancedUserPass=function(uid,serviceParamsPassword,responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"changeAdvancedUserPass?uid="+encodeURIComponent(uid.toString())
+"&serviceParamsPass="+encodeURIComponent(serviceParamsPassword),success:responseMethod,error:logError});}
Controller.prototype.getOwnerAddress=function(uid,responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getOwnerAddress?uid="+encodeURIComponent(uid),success:responseMethod,error:logError});};Controller.prototype.updateKey=function(key,uid){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"updateKey/?key="+encodeURIComponent(key)+"&uid="+encodeURIComponent(uid),success:confirmUpdatingkKey,error:logError});}
Controller.prototype.updateBlWhLists=function(whiteList,blackList,uid,responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"updateBlWhLists/?whiteList="+encodeURIComponent(whiteList)+"&blackList="+encodeURIComponent(blackList)+"&uid="+encodeURIComponent(uid),success:responseMethod,error:errorMethod});}
Controller.prototype.getEconetLog=function(uid,responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getEconetLog?uid="+encodeURIComponent(uid),success:responseMethod,error:errorMethod});}
Controller.prototype.getDeviceConfig=function(uid,responseMethod,errorMethod,file_prefix){var addparams=""
if(file_prefix!=null&&file_prefix==true){addparams="&file_prefix="+file_prefix}
$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getDeviceConfig?uid="+encodeURIComponent(uid)+addparams,success:responseMethod,error:errorMethod});}
Controller.prototype.isDevConfigFileExists=function(uid,responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"isDevConfigFileExists?uid="+encodeURIComponent(uid),success:responseMethod,error:errorMethod});}
Controller.prototype.getDevConfigFilesInfoDict=function(uid,responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getDevConfigFilesInfoDict?uid="+encodeURIComponent(uid),success:responseMethod,error:errorMethod});}
Controller.prototype.getUpdateStateElement=function(uid,responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getUpdateStateElement?uid="+encodeURIComponent(uid),success:responseMethod,error:errorMethod});}
Controller.prototype.getBlWhLists=function(uid,responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getBlWhLists?uid="+encodeURIComponent(uid),success:responseMethod,error:errorMethod});}
Controller.prototype.getEconetRegDp=function(uid,responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getRegGmDpTable?uid="+encodeURIComponent(uid),success:responseMethod,error:errorMethod});}
Controller.prototype.getProducersList=function(responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getProducersList",success:responseMethod,error:logError});}
Controller.prototype.getUserProducersList=function(responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getUserProducersList",success:responseMethod,error:logError});}
Controller.prototype.getDevSoftVers=function(responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getDevSoftVers",success:responseMethod,error:logError});}
Controller.prototype.getAdvancedUserPass=function(uid,responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"GetAdvancedUserPass?uid="+encodeURIComponent(uid),success:responseMethod,error:logError});}
Controller.prototype.deleteDevAlarms=function(uid,responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"deleteDevAlarms?uid="+encodeURIComponent(uid),success:responseMethod,error:logError});}
Controller.prototype.getCompany=function(responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getCompany",success:responseMethod,error:logError});return false;};Controller.prototype.submitRegSoft=function(data){$.ajax({type:"POST",url:this.destination_+"updateControllerSoft/",data:data,cache:false,dataType:'json',processData:false,contentType:false,error:logError,beforeSend:function(xhr){xhr.setRequestHeader("X-CSRFToken",Cookies.get('csrftoken'));},success:submitRegSoftResponse});return false;};Controller.prototype.setUpdateProgress=function(data){$.ajax({type:"POST",url:this.destination_+"setUpdateProgress/",data:data,cache:false,processData:false,contentType:false,error:logError,beforeSend:function(xhr){xhr.setRequestHeader("X-CSRFToken",Cookies.get('csrftoken'));},success:setUpdateStatusResponse});return false;};Controller.prototype.submitRegConfig=function(data){$.ajax({type:"POST",url:this.destination_+"updateControllerConfig/",data:data,cache:false,dataType:'json',processData:false,contentType:false,error:logError,beforeSend:function(xhr){xhr.setRequestHeader("X-CSRFToken",Cookies.get('csrftoken'));},success:submitRegConfigResponse});return false;};Controller.prototype.confirmUpdate=function(uid){$.ajax({type:"GET",contentType:"json",url:this.destination_+"confirmUpdate/?uid="+encodeURIComponent(uid),error:logError,});return false;};Controller.prototype.cancelUpdate=function(uid){$.ajax({type:"GET",contentType:"json",url:this.destination_+"cancelUpdate/?uid="+encodeURIComponent(uid),error:logError,success:cancelUpdateResponse});return false;};Controller.prototype.cancelDevConfUpload=function(uid){$.ajax({type:"GET",contentType:"json",url:this.destination_+"cancelDevConfUpload/?uid="+encodeURIComponent(uid),error:logError,success:cancelDevConfUploadResponse});return false;};Controller.prototype.getUpdateProgress=function(uid,responseMethod){$.ajax({type:"GET",contentType:"json",url:this.destination_+"getUpdateProgress/?uid="+encodeURIComponent(uid),error:logError,success:responseMethod});return false;};Controller.prototype.getUpdateConfigProgress=function(uid,responseMethod){$.ajax({type:"GET",contentType:"json",url:this.destination_+"getUpdateConfigProgress/?uid="+encodeURIComponent(uid),error:logError,success:responseMethod});return false;};Controller.prototype.getYieldHeats=function(uid,days,responseMethod){$.ajax({type:"POST",headers:{Accept:"text/plain","Content-Type":"application/x-www-form-urlencoded"},contentType:"json",data:{"uid":uid,"days":days},url:this.destination_+"getYieldHeats/",error:logError,success:responseMethod,beforeSend:function(xhr){xhr.setRequestHeader("X-CSRFToken",Cookies.get('csrftoken'));}});return false;};Controller.prototype.uploadMaintenanceDate=function(fromDate,toDate,dateNow,responseMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"uploadMaintenanceDate?fromDate="+encodeURIComponent(fromDate)
+"&toDate="+encodeURIComponent(toDate)
+"&dateNow="+encodeURIComponent(dateNow),error:logError,success:responseMethod,beforeSend:function(xhr){xhr.setRequestHeader("X-CSRFToken",Cookies.get('csrftoken'));}});return false;};Controller.prototype.restartDevice=function(responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"restartDevice?uid="+updater.currentDevice_,success:responseMethod,error:errorMethod});};Controller.prototype.getEconetLogFl=function(responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getEconetFlLog?uid="+updater.currentDevice_,success:responseMethod,error:errorMethod});};Controller.prototype.startEconetLogFl=function(responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"startEconetLogFl?uid="+updater.currentDevice_,success:responseMethod,error:errorMethod});};Controller.prototype.stopEconetLogFl=function(responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"stopEconetLogFl?uid="+updater.currentDevice_,success:responseMethod,error:errorMethod});};Controller.prototype.getFuelConsumption=function(fromDate,toDate,responseMethod,errorMethod){$.ajax({type:"GET",dataType:'json',cache:false,url:this.destination_+"getFuelConsumption?uid="+updater.currentDevice_+"&fromDate="+encodeURIComponent(fromDate)+"&toDate="+encodeURIComponent(toDate),success:responseMethod,error:errorMethod});};var lastReadModulesVersions=[]
function createVersionDivElement(lbIdBase){var row=document.createElement('div');$(row).addClass("econetFormLine");$(row).append('<label id="'+lbIdBase+'" class="econetFormLabel"></label><div class="econetFormText"><label id="'+lbIdBase+"Curr"+'"></label></div>');$('#devSettingsVersionsNrs').append(row);}
function updateModuleVersionRow(ver,moduleLabelName){if(ver!==null){if($("#"+moduleLabelName).length==0&&parent!=undefined){createVersionDivElement(moduleLabelName.substring(0,moduleLabelName.length-4));}
$("#"+moduleLabelName).parent().parent().show();$("#"+moduleLabelName).text(ver);}
else{$("#"+moduleLabelName).parent().parent().hide();}}
function updateModulesVersions(moduleASoftVer,moduleBSoftVer,moduleCSoftVer,moduleLambdaSoftVer,moduleEcoSTERSoftVer,modulePanelSoftVer){$("#moduleToUpdateSelect").empty();$("#devSettingsVersionsNrs").empty();updateModuleVersionRow(moduleASoftVer,"lbModuleAVerCurr");updateModuleVersionRow(moduleBSoftVer,"lbModuleBVerCurr");updateModuleVersionRow(moduleCSoftVer,"lbModuleCVerCurr");updateModuleVersionRow(moduleLambdaSoftVer,"lbLambdaModuleVerCurr");updateModuleVersionRow(modulePanelSoftVer,"lbPanelModuleVerCurr");updateModuleVersionRow(moduleEcoSTERSoftVer,"lbEcoSTERModuleVerCurr");}
function updateModulesVersionsFromArray(softVersion,modulesVersions,parentTableID){$("#moduleToUpdateSelect").empty();$("#devSettingsVersionsNrs").empty();var parent=document.getElementById(parentTableID);$('#lbSettingsSoftVerCurr').text(softVersion);for(var i in modulesVersions){var ver_desc=modulesVersions[i]
updateModuleVersionRow(ver_desc[1],ver_desc[0]);translateModulesVersions();}}
function reloadSelectVersions(){$("#moduleToUpdateSelect").empty();for(var i in lastReadModulesVersions){var ver_desc=lastReadModulesVersions[i]
if(ver_desc[0].substring(0,10)=="lbPanelVer"){name=MODULES_NAMES["lbPanelVerCurr"]+" "+ver_desc[0].split("_")[1].substring(0,3)+' (ver. '+ver_desc[1]+')';}
else{name=MODULES_NAMES[ver_desc[0]]+' (ver. '+ver_desc[1]+')';}
$("#moduleToUpdateSelect").append('<option value="'+ver_desc[0]+'">'+name+'</option>');}
$("#moduleToUpdateSelect").selectric('refresh');}
function translateModulesVersions(){$('#lbModuleAVer').text(translate("module_version").replace('@module','A'));$('#lbModuleBVer').text(translate("module_version").replace('@module','B'));$('#lbModuleCVer').text(translate("module_version").replace('@module','C'));$('#lbLambdaModuleVer').text(translate("module_version").replace('@module','Lambda'));$('#lbEcoSTERModuleVer').text(translate("module_version").replace('@module','ecoSTER'));$('#lbPanelModuleVer').text(translate("module_version").replace('@module','Panel'));$('#lbPanel1ModuleVer').text(translate("module_version").replace('@module','Panel 1'));$('#lbPanel2ModuleVer').text(translate("module_version").replace('@module','Panel 2'));$('#lbPanel3ModuleVer').text(translate("module_version").replace('@module','Panel 3'));$('#lbPanel4ModuleVer').text(translate("module_version").replace('@module','Panel 4'));$('#lbPanel5ModuleVer').text(translate("module_version").replace('@module','Panel 5'));$('#lbPanel6ModuleVer').text(translate("module_version").replace('@module','Panel 6'));$('#lbPanel7ModuleVer').text(translate("module_version").replace('@module','Panel 7'));$('#devSettingsVersionsNrs [id^="lbPanelVer_"]').each(function(){if($(this).attr("id").indexOf("Curr")==-1){$(this).text(translate("module_version").replace('@module','Panel '+$(this).attr("id").split("_")[1]));}});$('#lbPanelConfVer').text(translate("panels_conf"));$('#lbEcoSTERModuleVer1').text(translate("module_version").replace('@module','ecoSTER 1'));$('#lbEcoSTERModuleVer2').text(translate("module_version").replace('@module','ecoSTER 2'));$('#lbEcoSTERModuleVer3').text(translate("module_version").replace('@module','ecoSTER 3'));$('#lbPanelDownlConfVer').text(translate("panels_downl_conf"));$('#lbEcoIsm').text(translate("module_version").replace('@module','ecoISM'));}
SERVICE_VIEW='service_view';SERVICE_MODIFY='service_modify';SERVICE_NOT_ALLOWED='service_not_allowed';SERVICE_NOT_CLAIMED='not_owned';var devices_current_page=0;var devices_active=false;var devices_notactive=false;var devices_blocked=false;var devices_deviceType='';var devices_uid='';var devices_prodId='';var devices_softVer='';var devices_dict={};var devices=[];var addedAutocomleteInputs=false;var devAddressLabels=['devSettingsAddressTableLbStreetField','devSettingsAddressTableLbHouseField','devSettingsAddressTableLbPostalCodeField','devSettingsAddressTableLbCityField','devSettingsAddressTableLbCountryField']
var devDocAddressFields=['street','house','postalCode','city','country']
var devUserAddressLabels=['devUserSettingsAddressTableLbFnameField','devUserSettingsAddressTableLbLnameField','devUserSettingsAddressTableLbStreetField','devUserSettingsAddressTableLbHouseField','devUserSettingsAddressTableLbPostalCodeField','devUserSettingsAddressTableLbCityField','devUserSettingsAddressTableLbCountryField','devUserSettingsAddressTableLbEmailField','devUserSettingsAddressTableLbPhoneField']
var devDocUserAddressFields=['first_name','last_name','street','house','postalCode','city','country','email','phone']
var totalDevicesNumber=0;function generateDeviceImage(device_name,image_id){if((image_id===null)||(image_id===undefined)||(image_id<0)){image_id=0;}
if(image_id==0){let imagemap={'ecoTRONIC100':3,'ecoVENT':3,'ecoMAX360i':13,'ecoFLOOR':3,'e-GP':3};for(key in imagemap){if(device_name.startsWith(key)){image_id=imagemap[key];break;}}}
let style_id=String(image_id);if(style_id.length==1){style_id='0'+style_id;}
return'<i class="viewController'+style_id+'"></i>';}
function printDate(d){return d.toISOString();}
function setHeaderControllerLabel(uid,label){$('#topNavScrSubTitle').text(label+(uid!=label?' ('+uid+')':''));$('#topNavScrSubTitle').show();}
var createOnce=false;var select_versprods_options={language:{noResults:function(){return translate('no_res_found');},searching:function(){return translate('searching_ctrl');},inputTooShort:function(args){return translate('char_enter_need');},},allowClear:true,placeholder:"",theme:"sel2filterControl",}
var select_options={language:{noResults:function(){return translate('no_res_found');},searching:function(){return translate('searching_ctrl');},inputTooShort:function(args){return translate('char_enter_need');},},allowClear:true,placeholder:"",ajax:{url:null,dataType:'json',delay:100,data:function(params){return{term:params.term,};},processResults:function(data){return{results:$.map(data,function(obj){return{id:obj,text:obj};})};},cache:false},minimumInputLength:1,theme:"sel2filterControl",}
function setLogo(prodId){var file_name=deviceProducerImg(prodId);var producer_img='../static/pict/logos/'+file_name
var pimage_array=file_name.split(".");var producer_img2x='../static/pict/logos/'+pimage_array[0]+'-2x.'+pimage_array[1];var producer_img3x='../static/pict/logos/'+pimage_array[0]+'-3x.'+pimage_array[1];$('#logo').attr('src',producer_img);$('#logo').attr('srcset',(producer_img+' 1.5x, '+producer_img2x+' 2.5x, '+producer_img3x+' 3.5x'));}
function hideDeviceData(){cleanTiles();cleanParameters();cleanRMParameters();clearHistoryData();hideEconetLog();settings_ecosrv_soft_ver=null;$("#tabHrEmSchedules").hide();$('.lbDevInactive').hide();$('.lbDevIncompatybile').hide();$('#trLangSelection').hide()
$("#trPanelConfVer").hide();$("#trPanelVer").hide();$('#tabHrChart').hide();$("#tabHrSchedules").hide();$("#tabHrSchema").hide();$("#cntrTime").hide();$("#tabHrETSchedules").hide();$("#tabHrVentSchedules").hide();$("#tabHrServiceParams").hide();$("#tabHrUserParams").hide();$("#translationsErrorDiv").hide();$("#trPanelConfVer").hide();$("#tabAlarms").empty();$("#tabHrEmFuelConsum").hide();regAllowedAccess=true
clearFuelConsumData();clearETdata();PAR_SECTION_TITLE=[];controller.protocol_type="";schema=new Schema(window.location.protocol+'//'+window.location.host
+'/static/pict/schema/');tiles_params=[];new_tiles_params=[];tiles_tab=[];}
function deviceClick(uid,protocol,ng_av){if(totalDevicesNumber>1||!(isNormalUser())){$('#aDevices').show();}
drawTab=[];regAllowedAccess=true;controller.protocol_type=protocol;$('#deviceLeftPanelMobileM').removeAttr('style');$("#tabHrSchedules").hide();$("#tabHrEmSchedules").hide();$("#tabHrETSchedules").hide();$("#tabHrVentSchedules").hide();$('#tabHrEmFuelConsum').hide()
$("#lbPanelDownlConfVerCurr").text("");$("#trPanelDownlConfVer").hide();showPreloader();hideHistoryPreloader();updateCurrentDevice(uid);showTab('Data','Data');showHideDevAdminAreaButtons();setHeaderControllerLabel(uid,devices_dict[uid].label);updater.updateDev();getHistoryParamsCookies();if(isMemberOfGroup(GROUP_SERVICE)){controller.getOwnerAddress(uid,updateOwnerAddress);}else{$('#userDevAddressHeader').hide();$('#userDevAddressContent').hide();}
if((protocol=="em")||(protocol=="gm3_pomp")){$('#tabHrDevUpdate').show();$("#alarmsDelSect").show();}else{$('#tabHrDevUpdate').hide();$("#alarmsDelSect").hide();}
if(isDeviceGm3()){getDeletedTilesCookie();if(protocol=="gm3_pomp"){$("#cntrTime").show();$("#trPanelConfVer").show();$("#trPanelVer").show();initETSchedules();lastETpasswordVal=null;}
if(protocol=="gm3"&&checkCurrentDevActive()){$('#tabHrChart').show();}else{$('#tabHrChart').hide();}}
controller.getAdvancedUserPass(updater.currentDevice_,getAdvancedUserPassResponse);if(isMemberOfGroup(GROUP_ROOT)){$("#restartDeviceButton").show();$('#restartDeviceInfo').hide();}}
function updateDeviceInfo(result,textStatus,xmlhttprequest){devices_dict={};var devices=result.devices;var devices_to_select=[];for(k in devices){var device_json=devices[k];var device={};device.uid=device_json[0];device.label=device_json[2];device.time=device_json[3];device.serviceParamsEdit=device_json[22];device.state=device_json[21];devices_dict[device.uid]=device;devices_to_select.push(device.uid);}}
function createDevicesTable(result,textStatus,xmlhttprequest){try{if(result==null||'error'in result){if('error'in result){console.log(result.error);}
return;}
devices=result.devices;for(var ii in devices){if(typeof devices[ii][2]=="string"){devices[ii][2]=ngt.sanitize(devices[ii][2]);}
if(typeof devices[ii][11]=="string"){devices[ii][11]=ngt.sanitize(devices[ii][11]);}
if(typeof devices[ii][12]=="string"){devices[ii][12]=ngt.sanitize(devices[ii][12]);}
if(typeof devices[ii][13]=="string"){devices[ii][13]=ngt.sanitize(devices[ii][13]);}
if(typeof devices[ii][14]=="string"){devices[ii][14]=ngt.sanitize(devices[ii][14]);}
if(typeof devices[ii][15]=="string"){devices[ii][15]=ngt.sanitize(devices[ii][15]);}
if(typeof devices[ii][16]=="string"){devices[ii][16]=ngt.sanitize(devices[ii][16]);}
if(typeof devices[ii][17]=="string"){devices[ii][17]=ngt.sanitize(devices[ii][17]);}
if(typeof devices[ii][18]=="string"){devices[ii][18]=ngt.sanitize(devices[ii][18]);}}
resultTest=devices;updateDeviceInfo(result,textStatus,xmlhttprequest);if(totalDevicesNumber<result.devsNumber){totalDevicesNumber=result.devsNumber;}
let show_list=result.showSelection;if(show_list===undefined){show_list=(result.devsNumber>1)||(!isNormalUser());}
if(currentMenu=='Devices'&&!show_list){showDevice(devices[0]);$('#filtrOptions').hide();$('#mobileDevsFilterButton').hide();return;}
if(isMemberOfGroup(GROUP_MANAGEMENT)){$("#blockedCheck").show();}else{$("#blockedCheck").hide();}
if(result.nextPage||result.page>0){if(result.nextPage){$('#arrowRightImage').show();}else{$('#arrowRightImage').hide();}
if(result.page==0){$('#arrowLeftImage').hide();}else{$('#arrowLeftImage').show();}
if(result.nextPage){var pagesNum=parseInt(parseInt(result.devsNumber)/devices.length);if((parseInt(result.devsNumber)%devices.length)>0){pagesNum+=1;}}else{var pagesNum=parseInt(result.page)+1;}
var pageText=parseInt(result.page)+1+"/"+pagesNum;$('#currentPage').text(pageText);}else{$('#arrowLeftImage').hide();$('#arrowRightImage').hide();$('#currentPage').text("1/1");}
$('#devsNumber').text(translate('devs_number').replace('@value',result.devsNumber));$('#devs_loader').hide()
drawTable(devices);if(!addedAutocomleteInputs){addAutocompleteInputs();addedAutocomleteInputs=true;}}catch(e){console.log(e);}finally{hidePreloader();$('#devicesPanel').show();$('#sDevicesArea').show();}}
function drawTable(result){var str=[];var even_row=true;str.push('<table id="devicesTab">');showChangeDeviceBtn=true;if(isMemberOfGroup(GROUP_MANAGEMENT)){showChangeDeviceBtn=false;}
for(k in result){var device_json=result[k];var device=devices_dict[device_json[0]];var service_access=device_json[1];var protocolType=device_json[4];var controllerID=device_json[5];var softVer=device_json[6];var moduleAVer=(device_json[7]!=null?device_json[7]:'');var modulePanelVer=(device_json[8]!=null?device_json[8]:'');var eth0=device_json[9];var wlan0=device_json[10];var owner=(device_json[11]!=null?device_json[11]:'')+' '+(device_json[12]!=null?device_json[12]:'');var street=(device_json[13]!=null?device_json[13]:'');var house=(device_json[14]!=null?device_json[14]:'');var apartment=(device_json[15]!=null?device_json[15]:'');var postal_code=(device_json[16]!=null?device_json[16]:'');var city=(device_json[17]!=null?device_json[17]:'');var country=device_json[18];var reg_prod_id=device_json[19];var reg_img_id=device_json[20];var dev_state=device_json[21];var mac=device_json[23];var ext_ip=device_json[25];var prod_logo_id=device_json[26];var service_conn_time=device_json[28];var key=device_json[29];var ng_def=device_json[30];if(updater.serviceAccess_==SERVICE_NOT_ALLOWED||(updater.serviceAccess_==SERVICE_VIEW&&service_access==SERVICE_MODIFY)){service_access=updater.serviceAccess_;}
var showMenuStr=' onclick="showDevice(JSON.parse(decodeURIComponent(this.dataset.def)));" data-def=\''+encodeURIComponent(JSON.stringify(device_json))+'\' '
var td_common='<td class="ldContent">';var intable_common='<table>';var devBtn='<button class="econetBtn econetFormBlueBtn devSelBtn" '+showMenuStr+'>'+translate('choose')+'</button>';var address='';var addr_first_line=street+" "+house+(apartment?"/"+apartment:"");var addr_second_line=postal_code+" "+city;addr_second_line=addr_second_line.trim();if(country){if(addr_second_line){addr_second_line+=", "+country;}else{addr_second_line=country;}}
addr_first_line=addr_first_line.trim();addr_second_line=addr_second_line.trim();address=addr_first_line?(addr_first_line+"<br>"+addr_second_line):(addr_second_line);var device_time="---";if((device.time!==undefined)&&(device.time!==null)){device_time=convertUTCISOTime2LocalString(device.time);}
var device_img=generateDeviceImage(controllerID,reg_img_id);var service_access_img='';if((service_access==SERVICE_NOT_ALLOWED)||(service_access==SERVICE_NOT_CLAIMED)){service_access_img='<i class="lockDevicesIcon"></i>';}else if(service_access==SERVICE_VIEW){service_access_img='<i class="lockEyeDevicesIcon"></i>';}
switch(protocolType){case"em":var soft_ver_cell='<tr><td class="ldLabel ldVer">'
+translate('software_version_short')
+'</td><td class="ldValue">'
+softVer
+'</td></tr>'
+'<tr><td class="ldLabel ldVer">'
+translate("module_version_short").replace('@module','A')
+'</td><td class="ldValue">'
+moduleAVer
+'</td></tr>'
+'<tr><td class="ldLabel ldVer">'
+translate("module_version_short").replace('@module','Panel<br>')+'</td><td class="ldValue">'
+modulePanelVer+'</td></tr>';break;case"gm3":var soft_ver_cell='<tr><td class="ldLabel ldVer">'
+translate('software_version_short')
+'</td><td class="ldValue">'
+softVer
+'</td></tr>'
+'<tr><td class="ldLabel ldVer">'
+translate("module_version_short").replace('@module','Reg')+'</td><td class="ldValue">'+moduleAVer
+'</td></tr>';break;case"gm3_pomp":let _pvstr=''
if(modulePanelVer!==''){_pvstr=`<tr><td class="ldLabel ldVer">${translate("module_version_short").replace("@module","Panel")}</td><td class="ldValue">${modulePanelVer}</td></tr>`;}
var soft_ver_cell='<tr><td class="ldLabel ldVer">'
+translate('software_version_short')
+'</td><td class="ldValue">'
+softVer
+'</td></tr>'
+'<tr><td class="ldLabel ldVer">'
+translate("module_version_short").replace('@module','Reg')
+'</td><td class="ldValue">'+moduleAVer
+'</td></tr>'
+_pvstr;break;}
var ext_ip_label=''
if(ext_ip!=''){ext_ip_label='<tr><td class="ldLabel">'+translate('extip')+'</td><td class="ldValue">'+ext_ip+'</td></tr>';}
str.push('<tr class="'+(even_row?'even':'odd')+'" >'
+'<td class="ldIcon">'+device_img+'</td>'
+'<td class="ldMainInfo">'+intable_common
+'<tr><td class="ldLabel typeDevLabel">'+translate('type')
+'</td><td class="ldValue">'+controllerID
+'</td></tr><tr><td class="ldLabel idDevLabel">'+translate('id')
+'</td><td class="ldValue">'+device.uid
+'</td></tr><tr><td class="ldLabel nameDevLabel">'+translate('name')
+'</td><td class="ldValue">'+device.label
+'</td></tr>'+getDeviceProducerInfo(reg_prod_id)
+'</table></td>'+td_common+intable_common
+soft_ver_cell
+'</table></td>'+td_common+intable_common
+'<tr><td class="ldLabel netDevLabel">'+translate('net')
+'</td><td class="ldValue">'+eth0
+'</td></tr><tr><td class="ldLabel wifiDevLabel">'+translate('wifi')
+'</td><td class="ldValue">'+wlan0
+'</td></tr>'+ext_ip_label
+'</table></td>'+td_common+intable_common
+'<tr><td class="ldLabel ownerDevLabel">'+translate('owner')
+'</td><td class="ldValue">'+owner
+'</td></tr><tr><td class="ldLabel addressDevLabel">'+translate('address')
+'</td><td class="ldValue">'+address
+'</td></tr></table></td>'+td_common+intable_common
+getDeviceConnectionValue(service_conn_time)
+'<tr><td class="ldLabel activityDevLabel">'+translate('activity')
+'</td><td class="ldValue actDevLabel'+dev_state+'">'
+translate(dev_state)
+'</td></tr>'
+'<tr><td class="ldLabel lastObservationDevLabel">'+translate('last_observation')
+'</td><td class="ldValue">'+device_time+'</td></tr>'
+'<tr><td colspan="2" class="ldBtn">'+devBtn+'</td></tr>'
+'</table></td>'
+'<td class="devServiceAccess" >'+service_access_img
+(mac!=""&&isMemberOfGroup(GROUP_MANAGEMENT)&&dev_state=='blocked'?'<button type="button" class="updateKey econetBtn" id="'
+mac+';'+device.uid+'" title="'+translate("Update_key")
+'" onclick="return openUpdateKeyPopup(this.id, \''+key+'\');"><i class="keyDevicesIcon"></i></button>':'')+'</td>');even_row=!even_row;}
str.push('</table>');if(currentMenu=='Devices'){$('#devicesPanel').empty();$('#devicesPanel').append(str.join(""));}}
function getDeviceConnectionValue(connection_data){if(isMemberOfGroup(GROUP_ROOT)){if(connection_data!=null){return'<tr><td class="ldLabel connectionDevLabel">'
+translate('connecion_label')
+'</td><td class="ldValue connDevLabelactive">online</td></tr>'}else{return'<tr><td class="ldLabel connectionDevLabel">'
+translate('connecion_label')
+'</td><td class="ldValue connDevLabelnot_active">offline</td></tr>'}}else{return''}}
function getDeviceProducerInfo(producer_id){producer_label='';producer_name=$('#producersList option[value="'+producer_id+'"]').text()
if(producer_name.length>0){producer_label='<tr><td class="ldLabel prodDevLabel">'+translate('producer')
+':</td><td class="ldValue">'+producer_name+'</td></tr>'}
return producer_label;}
function updateCurrentDevice(uid){updater.setDeviceId(uid);if(uid){$('#devTabs').show();}else{$('#devTabs').hide();}}
function updateDeviceSysParamsEm(result){if(result.remoteMenu!=undefined){remoteMenu=result.remoteMenu;}
updateSysParamsCommon(result);}
function updateDeviceSysParamsET(result,textStatus,xmlhttprequest){updateSysParamsCommonET(result);}
function updateDeviceSysParamsGm(result,textStatus,xmlhttprequest){updateSysParamsCommon(result);}
function updateDeviceSysParams(result,textStatus,xmlhttprequest){try{if(result.error===undefined&&result.uid!==undefined){if(result.uid==updater.currentDevice_){if(result.protocolType=="em"){updateDeviceSysParamsEm(result);}else{if(result.etNewConfTrans!=undefined){etNewConfTrans=result.etNewConfTrans;if(etNewConfTrans){regConfig=etNewConfTrans}}
if(result.etConfVer!=undefined){etConfVer=result.etConfVer;}
if(isDeviceGm3Conf()){updateDeviceSysParamsET(result);createTilesET();}else{updateDeviceSysParamsGm(result);}}
if(remoteMenu||isDeviceGm3Conf()){$('#devAdvancedSettings').hide();}else{$('#devAdvancedSettings').show();}
updater.settingsParamsVer_=result.settingsParamsVer;updateAlarmsCall();updateSchedulesCall();reloadDeviceAddress(result.address);updateProperties(result.label,result.serviceAccess,result.alarmNotifications);current_soft_ver=result.softVer;namesResponse(result.panelsNames);updateTranslations();if(typeof current_soft_ver=="string"){let soft_ver=current_soft_ver.split('-')[0].split(".").map(d=>Number(d));if(soft_ver.length>=3){if(soft_ver[0]==3&&soft_ver[2]==3810){$('#newSoftUpdaterDl').show();$('#newSoftUpdater').hide();$('#newSoftVer').hide();}else if((soft_ver[0]==3&&soft_ver[2]>3810)){$('#newSoftUpdaterDl').hide();$('#newSoftUpdater').hide();$('#newSoftVer').hide();fetch('/aweb/f/en3upd/v2/check/'+updater.currentDevice_).then(d=>{if(d.status!=200){return;}
d.json().then(e=>{if(e.a&&e.v!=current_soft_ver){ngt.update(document.getElementById("newSoftUpdater").children[0],null,[e.v]);$('#newSoftUpdater').show();}});});}else{if(settings_ecosrv_soft_ver==null){controller.checkSoftUpdate(result.protocolType,result.routerType,checkSoftUpdateResponse);}}}}
if(result.logFl!=undefined){updateLogFlState(result.logFl);}}}}catch(e){console.log(e);}finally{hidePreloader();}}
function updateAlarmsCall(){controller.getDeviceAlarms(updater.currentDevice_,updateAlarmsResp);}
function updateAlarmsResp(result,textStatus,xmlhttprequest){alarmsResponse(result);}
function reloadDeviceAddress(address){if(address!=undefined){for(label in devAddressLabels){var addrLabel=devAddressLabels[label];$('#'+addrLabel).empty();}
if(isNotAnonymous()){if(isNotNormalUserNorAdmin()){for(label in devAddressLabels){var addrLabel=devAddressLabels[label];var docfieldLabel=devDocAddressFields[label];var value=ngt.sanitize((address[docfieldLabel]!=undefined)?address[docfieldLabel]:"")
var control="<label>"+value+"</label>"
$('#'+addrLabel).append(control);}}else{for(label in devAddressLabels){var addrLabel=devAddressLabels[label];var docfieldLabel=devDocAddressFields[label];var value=ngt.sanitize((address[docfieldLabel]!=undefined)?address[docfieldLabel]:"")
if(addrLabel.indexOf("devSettingsAddressTableLbCountryField")==-1){var control='<input value="'+value+'" id="'+addrLabel+'Inp">'
$('#'+addrLabel).append(control);}else{var control='<div><select id="'+addrLabel+'Inp"></div>'
$('#'+addrLabel).append(control);initCountriesSelCtrl(addrLabel+"Inp",currLang);$('#'+addrLabel+"Inp").val(value.toUpperCase());}}}}
$('#devAddressHeader').show();$('#devAddressContent').show();}else{$('#devAddressHeader').hide();$('#devAddressContent').hide();}}
function reloadDeviceUserAddress(address){if(address.cangetprotdata!=undefined&&address.cangetprotdata){if(isMemberOfGroup(GROUP_SERVICE)){$('#userDevAddressHeader').show();$('#userDevAddressContent').show();for(label in devUserAddressLabels){var addrLabel=devUserAddressLabels[label];var docfieldLabel=devDocUserAddressFields[label];var value=ngt.sanitize((address[docfieldLabel]!=undefined)?address[docfieldLabel]:"")
if(addrLabel.indexOf("devUserSettingsAddressTableLbCountryField")==-1){var control="<label>"+value+"</label>"
$('#'+addrLabel).html("")
$('#'+addrLabel).append(control);}else{var control="<label id=\"devUserSettingsAddressTableLbCountryValue\" code=\""+value+"\">"+getCountryByCodeInLang(value,currLang)+"</label>"
$('#'+addrLabel).html("")
$('#'+addrLabel).append(control);}}}}else{$('#userDevAddressHeader').hide();$('#userDevAddressContent').hide();}}
function updateOwnerAddress(result,textStatus,xmlhttprequest){if(!$.isEmptyObject(result)){result=JSON.parse(result);reloadDeviceUserAddress(result);}}
function updateProperties(label,serviceAccess,alarmNotifications){$('#inpRegLabel').val(label);$('#selServiceAccess').val(serviceAccess);$('#inpAlarmNotifications').prop('checked',alarmNotifications);}
function deviceSettingsTableProperlyFilled(tableId){var error=false;$("#"+tableId+' tr').each(function(index){if($(this).children().children('input').val()!=undefined)
if($(this).children().children('input').val().length==0&&$(this).children().children('span').length>0){error=true;$(this).children().children('span').text('*');}else{$(this).children().children('span').text('');}});return!error;}
function setDeviceAddressSettings(){controller.setDeviceAddressSettings(updater.currentDevice_,$('#devSettingsAddressTableLbStreetFieldInp').val(),$('#devSettingsAddressTableLbHouseFieldInp').val(),'',$('#devSettingsAddressTableLbPostalCodeFieldInp').val(),$('#devSettingsAddressTableLbCityFieldInp').val(),$('#devSettingsAddressTableLbCountryFieldInp').val(),setDeviceAddressSettingsResponse);}
function setDeviceSettings(){controller.setDeviceSettings(updater.currentDevice_,$('#inpRegLabel').val(),$('#selServiceAccess').val(),$('#inpAlarmNotifications').is(':checked'),setDeviceSettingsResponse);}
function setDeviceAddressSettingsResponse(result,textStatus,xmlhttprequest){if(result.hasOwnProperty("error")){var label=new ResultLabel($('#lbDevAddressSettingsResult'));label.showError(translate(result.error));}else{var label=new ResultLabel($('#lbDevAddressSettingsResult'));label.showInfo(translate('changes_saved'));}}
function setDeviceSettingsResponse(result,textStatus,xmlhttprequest){if(result.hasOwnProperty("error")){var label=new ResultLabel($('#lbDevSettingsResult'));label.showError(translate(result.error));}else{setHeaderControllerLabel(result.uid,result.label);var label=new ResultLabel($('#lbDevSettingsResult'));label.showInfo(translate('changes_saved'));}}
function completeProducersList(result,textStatus,xmlhttprequest){$('#producersList').empty();if(!$.isEmptyObject(result)){$('#producersList').append($("<option></option>").attr("value","").text("none"));for(var producer in result){$('#producersList').append($("<option></option>").attr("value",producer).text(result[producer]));}
if($('#producersList').select2!=undefined){select_versprods_options.placeholder=translate("filter_prod");$('#producersList').select2(select_versprods_options);}}}
function completeDevSoftVers(result,textStatus,xmlhttprequest){if(!$.isEmptyObject(result)){$('#verList').append($("<option></option>").attr("value","").text("none"));for(var suggestion in result.suggestions){$('#verList').append($("<option></option>").attr("value",result.suggestions[suggestion]).text(result.suggestions[suggestion]));}
select_versprods_options.placeholder=translate("filter_version");$('#verList').select2(select_versprods_options);}}
function resultProducersList(result,textStatus,xmlhttprequest){if(!$.isEmptyObject(result)){$('#producersList').append($("<option></option>").attr("value","").text("none"));for(var producer in result){$('#producersList').append($("<option></option>").attr("value",producer).text(result[producer]));}
if($('#producersList').select2!=undefined){select_versprods_options.placeholder=translate("filter_prod");$('#producersList').select2(select_versprods_options);}
$("#producersListArea").show();}else{$("#producersListArea").hide();}}
function addAutocompleteInputs(){select_options.placeholder=translate("filter_type");select_options.ajax.url=controller.destination_+"deviceTypes";$('#types_select').select2(select_options);$('#types_select').on("select2:unselect",function(e){$('#types_select').children().remove()});select_options.placeholder=translate("filter_uid");select_options.ajax.url=controller.destination_+"uids";$('#uid_select').select2(select_options);$('#uid_select').on("select2:unselect",function(e){$('#uid_select').children().remove()});}
function updateKey(key,uid){controller.updateKey(key,uid);}
function confirmUpdatingkKey(success){if(success){showConfirmLabelAndClose('editTextTwoOptPopupWindowInfoArea','editTextTwoOptPopup');}else{$("#editTextTwoOptPopupWindowInfoArea").text(translate("key_not_changed"));}}
function getNewFilteredDevices(){devices_current_page=0;devices_active=$('#active_state').is(':checked');devices_notactive=$('#notactive_state').is(':checked');devices_blocked=$('#blocked_state').is(':checked');devices_deviceType=$('#types_select').val()?$('#types_select').val():"";devices_uid=$('#uid_select').val()?$('#uid_select').val():"";devices_prodId=$('#producersList').val()?$('#producersList').val():"";devices_softVer=$('#verList').val()?$('#verList').val():"";getFilteredDevices();}
function getFilteredDevices(resultFunction){if(!resultFunction){resultFunction=createDevicesTable;}
controller.getDevices(resultFunction,devices_active,devices_notactive,devices_blocked,devices_deviceType,devices_uid,devices_prodId,devices_current_page,devices_softVer,$('#devfilter_ver_mod_a').val(),$('#devfilter_ver_panel').val());}
function showNextDevices(){showPreloader();++devices_current_page;getFilteredDevices();}
function showPrevDevices(){if(devices_current_page>0){showPreloader();--devices_current_page;getFilteredDevices();}}
function translateDeviceFilters(){$("#state").text(translate("activity"));$("#deviceType").text(translate("type"));$("#active").text(translate("active"));$("#notactive").text(translate("not_active"));$("#blocked").text(translate("blocked"));$("#submit_device_filter").val(translate("submit_devfilter"));$('#devsNumber').text(translate('devs_number').replace('@value',totalDevicesNumber));if($('#producersList').length>0&&$('#producersList').select2!=undefined){select_versprods_options.placeholder=translate("filter_prod");$('#producersList').select2(select_versprods_options);}
if($('#verList').length>0&&$('#verList').select2!=undefined){select_versprods_options.placeholder=translate("filter_version");$('#verList').select2(select_versprods_options);}}
var en300ng={submit_update:function(){let update_h="website"
let output={h:"website"}
let update_branch=document.getElementById("en300ng_updb").value.trim();if(update_branch.length>0){output.branch=update_branch;}
let update_version=document.getElementById("en300ng_updv").value.trim();if(update_version.length>0){output.version=update_version;}
let _data=JSON.stringify({en3upd:output});let csrf=ngh_getcsrf();jQuery.ajax('/aweb/d/gate/v2/appendState?uid='+updater.currentDevice_,{data:_data,error:en300ng.on_nothing,method:'POST',success:en300ng.on_nothing,headers:{'X-CSRFToken':csrf},contentType:'text/plain'});},on_nothing:function(){},update:function(){$.getJSON('/aweb/d/gate/v2/getState',{uid:updater.currentDevice_,_:jQuery.now()},en300ng.on_update_ok).error(en300ng.on_update_fail);},on_update_ok:function(resp){let answer="NO UPDATE";let x=resp.state.en3upd;if(x!==undefined&&x!==null){answer=x.state;}
document.getElementById("en300ng_state").textContent=answer;},on_update_fail:function(a,b,c){document.getElementById("en300ng_state").textContent="SERVER COMMUNICATION FAILED"}};